/// Flutter icons Manzel
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Manzel
///      fonts:
///       - asset: fonts/Manzel.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Manzel {
  Manzel._();

  static const _kFontFam = 'Manzel';
  static const String? _kFontPkg = null;

  static const IconData home_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData size = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bath = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancelled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData completed = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData living_room = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pending = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floor_plan = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData absher = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsApp_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_360 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1811 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maps2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confirm_booking = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_booking = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_icon = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1776 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1808 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1817 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1810 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1812 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1818 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_visit = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1813 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icon = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1820 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1805 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_icon_large = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_icon = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1803 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1806 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1819 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
